#pragma once

// Automatycznie utworzone z pliku rozwoj_niemowlaka_dzien_0_600.txt.
// Teksty zapisano bez polskich znakow, aby byly czytelne na domyslnym foncie LVGL.
#define DEVELOPMENT_TIP_COUNT 601
static const char * const DEVELOPMENT_TIPS[DEVELOPMENT_TIP_COUNT] PROGMEM = {
  /* 000 */ "Noworodek rozpoczyna adaptacje do zycia poza lonem matki, regulujac oddech, temperature i karmienie.",
  /* 001 */ "Dziecko wykorzystuje odruchy wrodzone, zwlaszcza ssania, szukania piersi i chwytania.",
  /* 002 */ "Rozpoznaje znany zapach opiekuna i uspokaja sie przy bliskim kontakcie.",
  /* 003 */ "Krotkie okresy czuwania sluza obserwowaniu twarzy i kontrastowych ksztaltow z bliska.",
  /* 004 */ "Wzrok najlepiej dziala na odleglosc mniej wiecej twarz-ramie podczas karmienia.",
  /* 005 */ "Dziecko komunikuje podstawowe potrzeby glownie placzem, ruchem i zmiana napiecia ciala.",
  /* 006 */ "Kontakt skora do skory pomaga mu regulowac cieplote ciala, oddech i poczucie bezpieczenstwa.",
  /* 007 */ "Pod koniec pierwszego tygodnia zaczyna zaznajamiac sie z rytmem karmienia i snu.",
  /* 008 */ "Noworodek moze na moment zatrzymac wzrok na twarzy opiekuna.",
  /* 009 */ "Reaguje na nagle, glosne dzwieki odruchem przestrachu lub mrugnieciem.",
  /* 010 */ "Krotkie momenty spokojnego czuwania staja sie okazja do budowania wiezi przez glos i dotyk.",
  /* 011 */ "Ruchy rak i nog sa jeszcze malo skoordynowane oraz czesto odruchowe.",
  /* 012 */ "Dziecko moze odwracac glowe w strone piersi lub zrodla znajomego zapachu.",
  /* 013 */ "W trakcie lezenia na brzuchu potrafi na chwile uniesc lub obrocic glowe.",
  /* 014 */ "Okolo drugiego tygodnia zaczyna stopniowo odzyskiwac mase urodzeniowa.",
  /* 015 */ "Coraz lepiej sygnalizuje glod, zmeczenie i potrzebe bliskosci.",
  /* 016 */ "Moze na krotko sledzic wzrokiem wolno poruszajacy sie obiekt o wysokim kontrascie.",
  /* 017 */ "Sluch rozwija sie przez codzienne osluchiwanie z glosami domownikow.",
  /* 018 */ "Dziecko uspokaja sie czesciej pod wplywem lagodnego, znajomego glosu.",
  /* 019 */ "Male dlonie zwykle pozostaja zacisniete, ale chwyt odruchowy jest wyrazny.",
  /* 020 */ "W czasie karmienia cwiczy koordynacje ssania, polykania i oddychania.",
  /* 021 */ "Pod koniec trzeciego tygodnia moze miec krotkie, bardziej uwazne okresy obserwacji otoczenia.",
  /* 022 */ "Dziecko zaczyna rozrozniac spokojne i bardziej intensywne bodzce w swoim otoczeniu.",
  /* 023 */ "Jego potrzeba rytmu i przewidywalnosci jest wspierana przez powtarzalna opieke.",
  /* 024 */ "Podczas lezenia na brzuchu podejmuje proby unoszenia glowy na kilka sekund.",
  /* 025 */ "Mimika twarzy moze przypominac usmiech, choc nie zawsze jest jeszcze reakcja spoleczna.",
  /* 026 */ "Dziecko coraz sprawniej dostraja sie do karmienia zgodnego z wlasnymi sygnalami glodu.",
  /* 027 */ "Przez krotka chwile moze skupiac wzrok na twarzy znajdujacej sie blisko.",
  /* 028 */ "Koniec czwartego tygodnia przynosi zwykle nieco wieksza czujnosc i zainteresowanie ludzmi.",
  /* 029 */ "Niemowle moze zaczac odpowiadac spokojem na znajomy glos lub kolysanie.",
  /* 030 */ "W drugim miesiacu rosnie zdolnosc do obserwowania twarzy i prostych wzorow.",
  /* 031 */ "Ruchy konczyn pozostaja gwaltowne, lecz pojawiaja sie krotkie chwile wiekszej plynnosci.",
  /* 032 */ "Dziecko cwiczy kontrole glowy podczas podnoszenia i noszenia w bezpiecznej pozycji.",
  /* 033 */ "Moze wykazywac wieksze zainteresowanie twarza mowiacego opiekuna.",
  /* 034 */ "Lezenie na brzuchu pod nadzorem wspiera wzmacnianie szyi, barkow i tulowia.",
  /* 035 */ "Dziecko coraz czesciej reaguje na obecnosc czlowieka spojrzeniem i uspokojeniem.",
  /* 036 */ "Wzrok stopniowo obejmuje wiecej szczegolow, zwlaszcza kontrastowych i wyraznych.",
  /* 037 */ "Podczas czuwania moze na moment obserwowac poruszajacy sie przedmiot.",
  /* 038 */ "Komunikacja nadal opiera sie glownie na placzu, ale opiekun zaczyna rozpoznawac jego rozne sygnaly.",
  /* 039 */ "Dziecko moze wydawac pierwsze spokojne dzwieki inne niz placz.",
  /* 040 */ "Okolo szostego tygodnia u czesci dzieci pojawia sie bardziej wyrazny usmiech spoleczny.",
  /* 041 */ "Usmiech w odpowiedzi na twarz lub glos jest poczatkiem intensywniejszej komunikacji spolecznej.",
  /* 042 */ "Dziecko moze dluzej utrzymywac spojrzenie na osobie znajdujacej sie blisko.",
  /* 043 */ "Podnosi glowe nieco pewniej podczas krotkiego lezenia na brzuchu.",
  /* 044 */ "Zaczyna reagowac na rozmowe mimika, spokojem albo drobnymi wokalizacjami.",
  /* 045 */ "Moze interesowac sie wlasnymi dlonmi, choc nie kontroluje ich jeszcze precyzyjnie.",
  /* 046 */ "Dziecko lepiej toleruje krotkie okresy aktywnosci miedzy drzemkami.",
  /* 047 */ "Pojedyncze gruchanie staje sie sposobem eksperymentowania z glosem.",
  /* 048 */ "Kiedy slyszy znajomy glos, moze odwracac oczy lub glowe w jego kierunku.",
  /* 049 */ "Pod koniec siodmego tygodnia interakcje twarz w twarz staja sie bardziej satysfakcjonujace dla dziecka.",
  /* 050 */ "Niemowle coraz czesciej obserwuje otoczenie w czasie spokojnego czuwania.",
  /* 051 */ "Moze na moment utrzymac glowe bardziej centralnie, gdy jest podtrzymywane.",
  /* 052 */ "Stopniowo zaczyna sledzic wzrokiem obiekt przesuwany z jednej strony na druga.",
  /* 053 */ "Dzwieki podobne do gruchania moga pojawiac sie w odpowiedzi na rozmowe.",
  /* 054 */ "Dziecko czesto uspokaja sie dzieki powtarzalnym, cieplym rytualom opieki.",
  /* 055 */ "Rece czasem otwieraja sie czesciej, a dlonie przypadkowo trafiaja do ust.",
  /* 056 */ "Pod koniec osmego tygodnia dziecko zwykle wyrazniej reaguje usmiechem na bliskie osoby.",
  /* 057 */ "Usmiech i kontakt wzrokowy wspieraja rozwoj bezpiecznej relacji z opiekunem.",
  /* 058 */ "Podczas lezenia na brzuchu moze unosic glowe pod wiekszym katem niz wczesniej.",
  /* 059 */ "Dziecko zaczyna wykazywac wieksze zaciekawienie prostymi zabawkami o kontrastowych barwach.",
  /* 060 */ "Okolo drugiego miesiaca moze swiadomie wydawac dzwieki w odpowiedzi na czlowieka.",
  /* 061 */ "Niemowle coraz czesciej \"rozmawia\" spojrzeniem, mimika i krotkimi odglosami.",
  /* 062 */ "Rytm dobowy nadal jest niedojrzaly, ale niektore dzieci zaczynaja miec dluzszy sen nocny.",
  /* 063 */ "Dziecko cwiczy miesnie szyi, probujac unosic glowe w lezeniu na brzuchu.",
  /* 064 */ "Moze z zainteresowaniem przygladac sie wlasnym dloniom poruszajacym sie przed twarza.",
  /* 065 */ "W odpowiedzi na lagodny glos czesciej pojawia sie spokojna uwaga lub usmiech.",
  /* 066 */ "Dziecko moze krotkotrwale utrzymac zabawke, jesli zostanie wlozona do jego dloni.",
  /* 067 */ "Zaczyna lepiej odrozniac codzienne dzwieki, glosy i intonacje.",
  /* 068 */ "W czasie zabawy warto zostawiac mu spokojna przestrzen na obserwacje i reakcje.",
  /* 069 */ "Podczas podnoszenia glowa moze nadal opadac, lecz kontrola szyi stopniowo sie poprawia.",
  /* 070 */ "Koniec dziesiatego tygodnia czesto oznacza wiecej gruchania, usmiechow i swiadomego kontaktu.",
  /* 071 */ "Dziecko moze reagowac ozywieniem na widok znanej twarzy.",
  /* 072 */ "Sledzenie wzrokiem ruchomego przedmiotu staje sie coraz plynniejsze.",
  /* 073 */ "Wokalizacje moga przybierac forme samogloskowych dzwiekow, takich jak \"aaa\" lub \"ooo\".",
  /* 074 */ "Niemowle coraz lepiej kontroluje ruch glowy w pozycji pionowej z podparciem.",
  /* 075 */ "Probuje badac swiat przez wkladanie dloni do ust i dotykanie twarzy.",
  /* 076 */ "Moze na chwile przerwac aktywnosc, aby nasluchiwac dzwieku.",
  /* 077 */ "Zainteresowanie ludzmi zwykle jest silniejsze niz zainteresowanie przedmiotami.",
  /* 078 */ "Dziecko moze coraz czesciej otwierac dlonie i ogladac wlasne palce.",
  /* 079 */ "Krotkie rozmowy, spiew i odpowiadanie na dzwieki wspieraja rozwoj komunikacji.",
  /* 080 */ "Okolo jedenastego tygodnia niemowle zaczyna przewidywac niektore powtarzalne elementy opieki.",
  /* 081 */ "Utrzymuje wzrok na twarzy dluzej i moze odpowiadac usmiechem na usmiech.",
  /* 082 */ "Podczas lezenia na brzuchu opiera sie coraz pewniej na przedramionach.",
  /* 083 */ "Ruchy rak moga czesciej kierowac sie w strone atrakcyjnego obiektu.",
  /* 084 */ "Dziecko staje sie bardziej ekspresyjne, uzywajac twarzy, ciala i glosu.",
  /* 085 */ "Moze zaczac rozpoznawac powtarzajace sie melodie, glosy lub rytualy.",
  /* 086 */ "Koordynacja wzrokowo-ruchowa rozwija sie, gdy obserwuje i probuje dosiegnac przedmiotu.",
  /* 087 */ "Niemowle stopniowo zdobywa wiecej sily w barkach i gornej czesci ciala.",
  /* 088 */ "Wspolna zabawa polegajaca na odpowiadaniu na jego dzwieki uczy naprzemiennosci.",
  /* 089 */ "Dziecko moze wyrazac zadowolenie bardziej wyraznym smiechem lub piskami.",
  /* 090 */ "Okolo trzeciego miesiaca wiele dzieci stabilniej trzyma glowe i aktywnie szuka kontaktu.",
  /* 091 */ "Niemowle moze obracac glowe za interesujacym dzwiekiem lub osoba.",
  /* 092 */ "Coraz czesciej laczy patrzenie na przedmiot z proba poruszenia reka w jego strone.",
  /* 093 */ "Moze swiadomie uderzac dlonia w lekka zabawke zawieszona w zasiegu wzroku.",
  /* 094 */ "Smiech bywa odpowiedzia na zabawe, laskotanie lub znajoma twarz.",
  /* 095 */ "Dziecko zaczyna zauwazac, ze jego ruchy moga powodowac ciekawe efekty.",
  /* 096 */ "Rece czesciej spotykaja sie w srodkowej linii ciala, co wspiera pozniejsza manipulacje.",
  /* 097 */ "Niemowle moze wkladac do ust palce jako sposob samouspokajania i poznawania ciala.",
  /* 098 */ "Zwieksza sie tolerancja na krotka aktywna zabawe na macie.",
  /* 099 */ "Dziecko moze wyrazniej protestowac, gdy jest zmeczone, glodne lub potrzebuje bliskosci.",
  /* 100 */ "Setny dzien to zwykle okres intensywnego rozwoju kontaktu spolecznego, glowy i rak.",
  /* 101 */ "Niemowle coraz sprawniej sledzi przedmiot przesuwany lukiem przed jego twarza.",
  /* 102 */ "Podczas lezenia na brzuchu moze unosic klatke piersiowa, opierajac sie na przedramionach.",
  /* 103 */ "Zaczyna dluzej bawic sie wlasnymi dlonmi, ogladajac je i wkladajac do ust.",
  /* 104 */ "Moze ozywiac sie na widok przygotowania do ulubionej zabawy lub karmienia.",
  /* 105 */ "Dziecko reaguje na zmiany tonu glosu, dostrzegajac roznice miedzy spokojem a energia.",
  /* 106 */ "Proby siegania sa jeszcze nieprecyzyjne, lecz staja sie coraz bardziej celowe.",
  /* 107 */ "Niemowle moze \"odpowiadac\" dzwiekiem po krotkiej pauzie w rozmowie.",
  /* 108 */ "Wspiera sie na lokciach, wzmacniajac miesnie potrzebne pozniej do obracania i pelzania.",
  /* 109 */ "Coraz czesciej przyciaga uwage usmiechem, wokalizacja i ruchami ciala.",
  /* 110 */ "Okolo trzeciego i pol miesiaca moze chwytac zabawke podana bezposrednio do reki.",
  /* 111 */ "Dziecko moze badac przedmiot przez potrzasanie nim, jesli potrafi go utrzymac.",
  /* 112 */ "Reaguje z wiekszym zainteresowaniem na wlasne odbicie w lustrze, choc go jeszcze nie rozpoznaje.",
  /* 113 */ "Podczas zabawy moze skupiac wzrok na kolorowym lub poruszajacym sie obiekcie.",
  /* 114 */ "Wokalizacje staja sie roznorodniejsze pod wzgledem wysokosci i glosnosci.",
  /* 115 */ "Dziecko cwiczy stabilnosc tulowia, gdy jest noszone pionowo z dobrym podparciem.",
  /* 116 */ "Moze zaczynac obracac sie na bok, wykorzystujac ruch nog, barkow i glowy.",
  /* 117 */ "Powtarzalne zabawy, takie jak \"a kuku\", buduja uwage i oczekiwanie.",
  /* 118 */ "Niemowle coraz lepiej sygnalizuje, kiedy potrzebuje przerwy od bodzcow.",
  /* 119 */ "Kontakt z roznymi bezpiecznymi fakturami rozwija dotykowe poznawanie swiata.",
  /* 120 */ "Okolo czwartego miesiaca czesc dzieci zaczyna samodzielnie obracac sie z brzucha na plecy.",
  /* 121 */ "Dziecko moze probowac dosiegnac obu rak do zabawki znajdujacej sie nad nim.",
  /* 122 */ "Stabilnosc glowy jest zwykle wyraznie lepsza podczas podnoszenia i noszenia.",
  /* 123 */ "Niemowle moze smiac sie glosniej i czesciej w odpowiedzi na wspolna zabawe.",
  /* 124 */ "Zaczyna przewidywac, ze powtarzalny ruch lub dzwiek zabawki zaraz sie wydarzy.",
  /* 125 */ "Rece i usta pozostaja glownymi narzedziami poznawania przedmiotow.",
  /* 126 */ "Dziecko moze probowac przetaczac sie na bok, aby zblizyc sie do interesujacego obiektu.",
  /* 127 */ "Coraz lepiej toleruje krotkie okresy zabawy na brzuchu.",
  /* 128 */ "W kontakcie spolecznym moze domagac sie dalszej zabawy, gdy dorosly przestaje reagowac.",
  /* 129 */ "Niemowle rozpoznaje codzienne glosy i czesto reaguje inaczej na osoby bliskie niz obce.",
  /* 130 */ "Okolo czwartego miesiaca rozwija wieksza kontrole rak oraz ciekawosc przyczyny i skutku.",
  /* 131 */ "Dziecko moze celowo chwycic lekka zabawke znajdujaca sie w zasiegu reki.",
  /* 132 */ "Przenosi wzrok miedzy przedmiotem a twarza opiekuna, cwiczac wspolna uwage.",
  /* 133 */ "Moze obracac sie z plecow na bok, przygotowujac sie do pelnego przewrotu.",
  /* 134 */ "Wydaje bardziej zlozone ciagi dzwiekow podczas zadowolenia lub rozmowy.",
  /* 135 */ "Zauwaza zmiany w otoczeniu i moze latwiej rozpraszac sie podczas karmienia.",
  /* 136 */ "Dziecko uzywa rak w sposob coraz bardziej symetryczny i celowy.",
  /* 137 */ "Probuje zblizyc zabawke do ust, aby poznac jej ksztalt i fakture.",
  /* 138 */ "W czasie lezenia na brzuchu moze prostowac rece bardziej niz wczesniej.",
  /* 139 */ "Uczy sie naprzemiennosci, gdy dorosly reaguje na jego smiech i dzwieki.",
  /* 140 */ "Koniec dwudziestego tygodnia czesto przynosi wiecej ruchliwosci i checi eksploracji.",
  /* 141 */ "Niemowle moze zaczac obracac sie z plecow na brzuch, choc tempo tej umiejetnosci jest bardzo rozne.",
  /* 142 */ "Dluzej utrzymuje sie na brzuchu, obserwujac zabawki i ludzi.",
  /* 143 */ "Dziecko siega po przedmioty bardziej konsekwentnie, choc nie zawsze trafia dokladnie.",
  /* 144 */ "Moze odkrywac swoje stopy, chwytajac je podczas lezenia na plecach.",
  /* 145 */ "Gaworzenie staje sie bogatsze w piskliwe, gardlowe i samogloskowe dzwieki.",
  /* 146 */ "Reaguje na emocje opiekuna, uspokajajac sie lub ozywiajac pod wplywem tonu glosu.",
  /* 147 */ "Niemowle moze obserwowac spadajacy przedmiot, uczac sie podstaw trwalosci i ruchu.",
  /* 148 */ "Rozwija sie zdolnosc chwytania zabawki cala dlonia.",
  /* 149 */ "Dziecko moze przenosic przedmiot z jednej reki do drugiej, choc nie u kazdego dzieje sie to juz teraz.",
  /* 150 */ "Okolo piatego miesiaca rosnie ciekawosc swiata i potrzeba aktywnej zabawy.",
  /* 151 */ "Niemowle moze odpychac sie stopami od podloza, gdy jest podtrzymywane pionowo.",
  /* 152 */ "Z zainteresowaniem manipuluje miekkimi, lekkimi i bezpiecznymi zabawkami.",
  /* 153 */ "Coraz czesciej sprawdza, co sie stanie, gdy potrzasnie, stuknie lub upusci przedmiot.",
  /* 154 */ "Dziecko moze rozpoznawac swoje imie po powtarzajacym sie brzmieniu, ale nie jest to jeszcze regula.",
  /* 155 */ "Przy znanych osobach bywa bardziej otwarte, a wobec nowych twarzy uwazniej obserwuje.",
  /* 156 */ "Odkrywa zaleznosc miedzy ruchem wlasnego ciala a zmiana pozycji na macie.",
  /* 157 */ "Podczas lezenia na brzuchu moze obracac sie wokol wlasnej osi, probujac dosiegnac obiektu.",
  /* 158 */ "Wokalizacje moga przypominac dialog, gdy dziecko robi przerwy po wypowiedzi doroslego.",
  /* 159 */ "Umiejetnosc skupienia uwagi na zabawie stopniowo wydluza sie.",
  /* 160 */ "Dziecko moze zaczac siedziec z wyraznym podparciem, kontrolujac glowe i gorna czesc tulowia.",
  /* 161 */ "Niemowle coraz aktywniej bada zabawki przez obracanie, potrzasanie i wkladanie do ust.",
  /* 162 */ "Moze odrozniac bardziej znajome osoby od obcych dzieki twarzom, glosom i rytualom.",
  /* 163 */ "Zaczyna lepiej kontrolowac obie rece podczas siegania do przedmiotu.",
  /* 164 */ "Dziecko moze probowac podciagac klatke piersiowa wyzej w pozycji na brzuchu.",
  /* 165 */ "Pojawia sie wiecej oznak radosci z interakcji, takich jak smiech, piski i machanie rekami.",
  /* 166 */ "Niemowle moze celowo przyciagac zabawke do siebie, gdy znajduje sie blisko.",
  /* 167 */ "Coraz wyrazniej odwraca uwage lub protestuje, kiedy ma dosc bodzcow.",
  /* 168 */ "Okolo szostego miesiaca czesc dzieci zaczyna samodzielnie obracac sie w obie strony.",
  /* 169 */ "Dziecko moze siedziec przez krotka chwile z niewielkim podparciem, opierajac rece z przodu.",
  /* 170 */ "Wiele niemowlat zaczyna interesowac sie jedzeniem rodziny, co moze byc jednym z sygnalow gotowosci do rozszerzania diety.",
  /* 171 */ "Gotowosc do nowych pokarmow ocenia sie calosciowo, zwracajac uwage na stabilnosc siedzenia, kontrole glowy i zainteresowanie jedzeniem.",
  /* 172 */ "Dziecko moze probowac chwytac male kawalki jedzenia cala dlonia, jesli dieta jest juz rozszerzana zgodnie z zaleceniami specjalisty.",
  /* 173 */ "Wkladanie bezpiecznych przedmiotow do ust nadal jest waznym sposobem poznawania.",
  /* 174 */ "Niemowle moze reagowac na swoje imie lub na czesto powtarzane, charakterystyczne slowa.",
  /* 175 */ "Gaworzenie wzbogaca sie o dzwieki przypominajace spolgloski, na przyklad \"m\" i \"b\".",
  /* 176 */ "Dziecko moze ogladac przedmiot, ktory upadl, i szukac go wzrokiem.",
  /* 177 */ "Zyskuje wieksza stabilnosc w siadzie z podparciem i podczas zmiany pozycji.",
  /* 178 */ "Moze porownywac zabawki, wybierajac te bardziej kolorowa, dzwieczna lub znajoma.",
  /* 179 */ "Dziecko uczy sie, ze jego zachowanie wywoluje reakcje doroslego.",
  /* 180 */ "Okolo szostego miesiaca rozwoj ruchowy, spoleczny i poznawczy staje sie szczegolnie widoczny w codziennej zabawie.",
  /* 181 */ "Niemowle moze przekladac zabawke z reki do reki z coraz wieksza swoboda.",
  /* 182 */ "Zaczyna aktywnie siegac po przedmiot poza centralna linia ciala.",
  /* 183 */ "Dziecko moze obracac sie na brzuch, aby lepiej obserwowac otoczenie.",
  /* 184 */ "Probuje podpierac sie prostymi rekami, wzmacniajac obrecz barkowa.",
  /* 185 */ "Wokalizacje moga przyjmowac rytm przypominajacy \"rozmowe\".",
  /* 186 */ "Niemowle coraz lepiej odczytuje emocjonalny ton glosu opiekuna.",
  /* 187 */ "Moze zaczac reagowac ostrozniej na obce osoby, co jest naturalnym elementem rozwoju spolecznego.",
  /* 188 */ "Dziecko rozwija pamiec codziennych rytualow, takich jak kapiel, karmienie i zasypianie.",
  /* 189 */ "Podczas zabawy moze probowac dosiegnac przedmiotu oddalonego nieco poza zasiegiem.",
  /* 190 */ "Koniec okolo siodmego miesiaca czesto przynosi wieksza samodzielnosc w przemieszczaniu sie po macie przez obracanie i turlanie.",
  /* 191 */ "Niemowle moze samodzielnie siedziec przez chwile, gdy ma dobre podparcie lub szeroka baze.",
  /* 192 */ "Zainteresowanie przedmiotami rosnie, gdy dziecko uczy sie je ogladac z roznych stron.",
  /* 193 */ "Moze stukac zabawkami o siebie lub o podloze, sprawdzajac ich dzwiek.",
  /* 194 */ "Dziecko zaczyna rozumiec prosta powtarzalnosc: potrzasniecie zabawka moze wywolac dzwiek.",
  /* 195 */ "Podczas karmienia uczy sie nowych konsystencji i ruchow jamy ustnej, jesli rozszerzanie diety juz trwa.",
  /* 196 */ "Niemowle moze wyciagac rece do osoby, z ktora chce miec kontakt.",
  /* 197 */ "Wykazuje preferencje wobec zabawek, piosenek i sposobow zabawy.",
  /* 198 */ "Moze probowac przesuwac ciezar ciala w lezeniu na brzuchu, przygotowujac sie do pelzania.",
  /* 199 */ "Dziecko moze powtarzac sylaby w rodzaju \"ba-ba\" lub \"ma-ma\", jeszcze bez znaczenia slowa.",
  /* 200 */ "Okolo dwusetnego dnia eksploracja przedmiotow i przemieszczanie sie staja sie wazna czescia dnia.",
  /* 201 */ "Niemowle moze odwracac sie w strone zrodla dzwieku z wieksza precyzja.",
  /* 202 */ "Siedzenie z podparciem staje sie stabilniejsze, a rece moga byc bardziej dostepne do zabawy.",
  /* 203 */ "Dziecko zaczyna uzywac obu rak do ogladania wiekszego przedmiotu.",
  /* 204 */ "Moze przewidywac koniec znanej piosenki lub zabawy po jej rytmie.",
  /* 205 */ "W relacji z opiekunem wyrazniej pokazuje radosc, frustracje i potrzebe bliskosci.",
  /* 206 */ "Niektore dzieci zaczynaja pelzac do tylu lub obracac sie, aby dotrzec do celu.",
  /* 207 */ "Niemowle moze probowac dosiegnac zabawki jedna reka, podpierajac sie druga.",
  /* 208 */ "Stopniowo rozwija chwyt dloniowy, obejmujac przedmioty wszystkimi palcami.",
  /* 209 */ "Dziecko coraz czesciej reaguje na proste, czesto uzywane slowa w kontekscie.",
  /* 210 */ "Okolo siodmego miesiaca rosnie gotowosc do samodzielnego badania najblizszego otoczenia.",
  /* 211 */ "Niemowle moze utrzymywac stabilniejszy siad z minimalnym podparciem, lecz zawsze wymaga bezpiecznej przestrzeni.",
  /* 212 */ "Probuje zmieniac pozycje z lezenia na brzuchu do boku i z powrotem.",
  /* 213 */ "Dziecko moze coraz pewniej siegac po zabawke poza zasiegiem, przesuwajac cialo do przodu.",
  /* 214 */ "Rozpoznaje znajome melodie i moze reagowac na nie ozywieniem.",
  /* 215 */ "Gaworzenie bywa bardziej rytmiczne, z powtarzanymi ciagami sylab.",
  /* 216 */ "Niemowle moze szukac wzrokiem przedmiotu czesciowo zaslonietego przez material.",
  /* 217 */ "Uczy sie, ze ludzie i rzeczy moga nadal istniec, nawet gdy chwilowo nie sa widoczne.",
  /* 218 */ "Moze silniej protestowac przy rozstaniu z glownym opiekunem, poniewaz lepiej rozpoznaje bliskie osoby.",
  /* 219 */ "Dziecko cwiczy rownowage, siedzac i siegajac po przedmioty w roznych kierunkach.",
  /* 220 */ "Okolo konca siodmego miesiaca wiele dzieci zaczyna sprawniej zmieniac pozycje na podlodze.",
  /* 221 */ "Niemowle moze przemieszczac sie przez turlanie, obrot wokol osi lub pelzanie.",
  /* 222 */ "Coraz lepiej uzywa dloni do chwytania i uwalniania przedmiotow, choc puszczanie bywa jeszcze przypadkowe.",
  /* 223 */ "Dziecko moze celowo upuszczac zabawke, aby obserwowac reakcje doroslego albo dzwiek upadku.",
  /* 224 */ "Rozumie coraz wiecej z tonu glosu, gestow i powtarzanych sytuacji.",
  /* 225 */ "Moze reagowac na proste prosby, jesli towarzyszy im staly gest lub kontekst.",
  /* 226 */ "Niemowle rozwija ostroznosc wobec nowych osob i miejsc, szukajac spojrzeniem opiekuna.",
  /* 227 */ "Podczas zabawy moze przekladac przedmioty, laczyc je i ogladac ich skutki.",
  /* 228 */ "Dziecko wzmacnia nogi, odbijajac sie i probujac utrzymac ciezar ciala przy podtrzymaniu.",
  /* 229 */ "Pojawiaja sie proby przyjmowania pozycji na czworakach lub unoszenia bioder, ale nie u kazdego dziecka w tym samym czasie.",
  /* 230 */ "Okolo siedmiu i pol miesiaca dziecko zwykle ma wyrazna potrzebe ruchu oraz samodzielnego odkrywania.",
  /* 231 */ "Niemowle moze stabilnie siedziec samodzielnie przez coraz dluzszy czas, jesli samo osiagnelo te pozycje.",
  /* 232 */ "Uczy sie utrzymywac rownowage podczas siegania po przedmiot i wracania do pionu.",
  /* 233 */ "Dziecko moze zaczac pelzac do przodu, przesuwajac sie brzuchem po podlodze.",
  /* 234 */ "Probuje przechodzic z siadu na bok, aby siegnac po zabawke.",
  /* 235 */ "Zainteresowanie drobnymi szczegolami przedmiotow staje sie bardziej widoczne.",
  /* 236 */ "Niemowle moze probowac podnosic male elementy palcami, choc chwyt pesetowy rozwinie sie pozniej.",
  /* 237 */ "Rozwija sie rozumienie prostych zaleznosci, na przyklad ze ukryta zabawka moze byc pod kocykiem.",
  /* 238 */ "Dziecko moze rozpoznawac stale slowa uzywane w codziennych sytuacjach, takie jak \"pa pa\" lub \"am\".",
  /* 239 */ "Gaworzenie moze brzmiec jak dluzsze \"wypowiedzi\" z rozna intonacja.",
  /* 240 */ "Okolo osmego miesiaca niemowle coraz intensywniej laczy ruch, komunikacje i odkrywanie przyczyny oraz skutku.",
  /* 241 */ "Dziecko moze zaczac przesuwac sie na czworakach do tylu lub kolysac w tej pozycji.",
  /* 242 */ "Kazda bezpieczna okazja do zabawy na podlodze wspiera samodzielne cwiczenie ruchu.",
  /* 243 */ "Niemowle moze wybierac zabawke, po ktora chce siegnac, i ignorowac mniej interesujaca.",
  /* 244 */ "Coraz czesciej sprawdza trwalosc przedmiotu, rzucajac nim, stukajac nim lub sciskajac go.",
  /* 245 */ "Moze szukac opiekuna wzrokiem, gdy ten wychodzi poza pole widzenia.",
  /* 246 */ "Reaguje na swoje imie czesciej i bardziej konsekwentnie, szczegolnie w spokojnym otoczeniu.",
  /* 247 */ "Dziecko moze uczestniczyc w prostych zabawach naprzemiennych, na przyklad podawaniu przedmiotu.",
  /* 248 */ "Zaczyna rozumiec, ze gest doroslego moze wskazywac wazny obiekt lub dzialanie.",
  /* 249 */ "Niemowle moze nasladowac proste dzwieki, mimike lub ruchy twarzy.",
  /* 250 */ "Okolo osmego miesiaca rozwija sie bardziej celowa komunikacja przedjezykowa.",
  /* 251 */ "Dziecko moze przesuwac sie do przodu przez pelzanie, raczkowanie lub inny wlasny sposob lokomocji.",
  /* 252 */ "Przejscie do pozycji na czworakach wzmacnia rece, biodra i miesnie tulowia.",
  /* 253 */ "Niemowle moze wyciagac rece do opiekuna, aby poprosic o podniesienie.",
  /* 254 */ "Uczy sie, ze jego gesty i dzwieki maja wplyw na zachowanie doroslych.",
  /* 255 */ "Moze wkladac i wyjmowac wieksze przedmioty z pojemnika, jesli sa bezpieczne i odpowiednio duze.",
  /* 256 */ "Dziecko coraz sprawniej puszcza przedmiot, gdy chce wziac inny.",
  /* 257 */ "Wspolne ogladanie ksiazeczek obrazkowych rozwija uwage, jezyk i wspolna zabawe.",
  /* 258 */ "Niemowle moze z zainteresowaniem ogladac odbicie w lustrze i dotykac jego powierzchni.",
  /* 259 */ "Pojawia sie wieksza wrazliwosc na rozlake, poniewaz wiez z opiekunem jest coraz silniej rozpoznawana.",
  /* 260 */ "Okolo konca osmego miesiaca dziecko jest zwykle bardziej mobilne i coraz skuteczniej komunikuje potrzeby.",
  /* 261 */ "Niemowle moze samodzielnie przemieszczac sie na odleglosc w wybrany przez siebie sposob.",
  /* 262 */ "Stara sie przyciagac przedmioty i ludzi, uzywajac ruchu, glosu oraz spojrzenia.",
  /* 263 */ "Dziecko moze zaczac podciagac sie przy stabilnym meblu, gdy rozwoj ruchowy do tego dojrzeje.",
  /* 264 */ "Proby stania przy podparciu wymagaja zabezpieczenia przestrzeni przed upadkiem i dostepem do niebezpiecznych przedmiotow.",
  /* 265 */ "Niemowle moze podawac zabawke doroslemu, choc nie zawsze oznacza to chec oddania jej na stale.",
  /* 266 */ "Rozumie prosta gre \"daj-wez\" poprzez powtarzanie sytuacji z opiekunem.",
  /* 267 */ "Dziecko moze szukac przedmiotu, ktory zostal calkowicie ukryty na jego oczach.",
  /* 268 */ "Gaworzenie nabiera wyrazniejszego rytmu jezykowego, z powtarzaniem sylab i zmianami tonu.",
  /* 269 */ "Niemowle moze machac reka w odpowiedzi na gest pozegnania, zwlaszcza po wielokrotnym modelowaniu.",
  /* 270 */ "Okolo dziewiatego miesiaca dziecko coraz czesciej laczy gesty, dzwieki i celowe dzialania.",
  /* 271 */ "Dziecko moze stabilniej siedziec, obracac tulow i siegac po zabawke bez szybkiej utraty rownowagi.",
  /* 272 */ "Coraz czesciej przemieszcza sie, aby zdobyc interesujacy przedmiot.",
  /* 273 */ "Niemowle moze podciagac sie do stania przy stabilnym podparciu.",
  /* 274 */ "W pozycji stojacej z podparciem przenosi ciezar z nogi na noge.",
  /* 275 */ "Dziecko rozwija chwyt nozycowy, uzywajac kciuka i bokow palcow do podnoszenia drobniejszych rzeczy.",
  /* 276 */ "Moze probowac wkladac male elementy do wiekszego pojemnika, zawsze pod scislym nadzorem ze wzgledu na ryzyko zadlawienia.",
  /* 277 */ "Rozumie coraz wiecej prostych slow powiazanych z codzienna rutyna.",
  /* 278 */ "Niemowle moze reagowac na proste komunikaty, takie jak \"chodz\" lub \"daj\", jesli sa czesto uzywane w kontekscie.",
  /* 279 */ "Uczy sie nasladowac proste gesty, na przyklad klaskanie lub machanie.",
  /* 280 */ "Koniec czterdziestego tygodnia zwykle przynosi wieksza sprawnosc rak, mobilnosc i zaangazowanie spoleczne.",
  /* 281 */ "Niemowle moze raczkowac, pelzac lub przemieszczac sie w inny indywidualny sposob.",
  /* 282 */ "Dziecko coraz pewniej zmienia pozycje miedzy siadem, czworakami i staniem przy podparciu.",
  /* 283 */ "Moze badac mechanizmy zabawek, popychajac, otwierajac lub zamykajac proste elementy.",
  /* 284 */ "Wspolna zabawa w nasladowanie pomaga rozwijac pamiec, uwage i komunikacje.",
  /* 285 */ "Dziecko moze reagowac radoscia na znajome piosenki, zabawy paluszkowe i rytualy.",
  /* 286 */ "Coraz wyrazniej wskazuje preferencje dotyczace jedzenia, zabawek lub osob.",
  /* 287 */ "Niemowle moze podnosic drobne okruszki bardziej precyzyjnie, ale wszystkie male przedmioty powinny pozostawac poza zasiegiem.",
  /* 288 */ "Pojawiaja sie proby picia z otwartego kubka lub kubka treningowego z pomoca doroslego.",
  /* 289 */ "Dziecko moze okazywac niezadowolenie, gdy dorosly zabiera atrakcyjny przedmiot.",
  /* 290 */ "Okolo dziewieciu i pol miesiaca niemowle intensywnie cwiczy samodzielnosc w ruchu i komunikacji.",
  /* 291 */ "Dziecko moze przechodzic bokiem przy meblach, jesli wczesniej potrafi stabilnie stanac z podparciem.",
  /* 292 */ "Podczas stania przy podparciu cwiczy rownowage przez puszczanie jednej reki.",
  /* 293 */ "Niemowle moze celowo wracac do opiekuna po wsparcie, gdy napotyka nowa sytuacje.",
  /* 294 */ "Rozumienie prostych zakazow i granic zaczyna sie rozwijac, choc dziecko nadal wymaga spokojnego przekierowania.",
  /* 295 */ "Moze powtarzac dzwieki, ktore wywoluja reakcje doroslych.",
  /* 296 */ "Dziecko moze probowac nasladowac dzialania w domu, takie jak przykladanie telefonu do ucha.",
  /* 297 */ "Uczy sie, ze przedmiot istnieje takze wtedy, gdy nie jest widoczny, i aktywniej go poszukuje.",
  /* 298 */ "Niemowle moze wskazywac reka lub siegac w kierunku interesujacego celu.",
  /* 299 */ "Zwieksza sie zdolnosc skupienia na prostej czynnosci przez kilka chwil.",
  /* 300 */ "Trzystny dzien przypada zwykle na okres wzmozonej mobilnosci, ciekawosci i komunikacji gestem.",
  /* 301 */ "Dziecko moze kontrolowac puszczanie przedmiotow bardziej swiadomie, wkladajac je do pojemnika.",
  /* 302 */ "Niemowle moze z zainteresowaniem otwierac szuflady lub drzwiczki, dlatego zabezpieczenia domu staja sie szczegolnie wazne.",
  /* 303 */ "Probuje przesuwac przedmioty, aby dostac sie do tego, czego chce.",
  /* 304 */ "Dziecko moze uzywac jednego przedmiotu do uzyskania drugiego, na przyklad odsuwac przeszkode od zabawki.",
  /* 305 */ "Wspolne czytanie wspiera rozpoznawanie obrazkow i brzmienia slow.",
  /* 306 */ "Niemowle moze reagowac na proste pytanie przez spojrzenie w strone znanego obiektu.",
  /* 307 */ "Coraz czesciej inicjuje kontakt, wydajac dzwiek, podajac zabawke lub przyciagajac uwage.",
  /* 308 */ "Dziecko moze wyrazac niepewnosc wobec nowych miejsc, ale uspokaja sie w obecnosci zaufanego opiekuna.",
  /* 309 */ "Ruchy podczas raczkowania lub chodzenia przy meblach staja sie coraz bardziej wydajne.",
  /* 310 */ "Okolo dziesiatego miesiaca dziecko zdobywa wiele informacji przez samodzielna eksploracje domu.",
  /* 311 */ "Niemowle moze zaczac celowo wskazywac przedmiot cala reka albo wyciagnietym palcem.",
  /* 312 */ "Gest wskazywania rozwija wspolna uwage, gdy dorosly nazywa to, czym zainteresowalo sie dziecko.",
  /* 313 */ "Dziecko moze probowac nasladowac odglosy zwierzat, pojazdow lub proste sylaby.",
  /* 314 */ "Coraz lepiej rozumie rutynowe komunikaty polaczone z gestem, takie jak \"chodzmy\" albo \"pa pa\".",
  /* 315 */ "Niemowle moze przesuwac sie wzdluz mebli, trzymajac sie obiema rekami.",
  /* 316 */ "Probuje schylac sie po zabawke, pozostajac przy podparciu.",
  /* 317 */ "Dziecko rozwija precyzje palcow, chwytajac drobniejsze bezpieczne elementy jedzenia.",
  /* 318 */ "Moze probowac samodzielnie wkladac lyzeczke do ust, choc potrzebuje pomocy i cierpliwosci.",
  /* 319 */ "W zabawie z pojemnikami cwiczy wkladanie, wyjmowanie i przewidywanie efektu.",
  /* 320 */ "Okolo dziesieciu i pol miesiaca rosnie wyrazna chec samodzielnego dzialania.",
  /* 321 */ "Niemowle moze przechodzic od mebla do mebla, jesli odleglosc jest mala i podparcie stabilne.",
  /* 322 */ "Dziecko moze chwilowo stac bez trzymania, ale nie jest to oczekiwane u wszystkich na tym etapie.",
  /* 323 */ "Proby samodzielnego picia rozwijaja koordynacje dloni, ust i tulowia.",
  /* 324 */ "Niemowle moze rozpoznawac nazwy kilku znanych osob lub przedmiotow.",
  /* 325 */ "Coraz czesciej uzywa gestow, aby poprosic, odmowic lub podzielic sie zainteresowaniem.",
  /* 326 */ "Dziecko moze nasladowac proste czynnosci domowe w zabawie.",
  /* 327 */ "Wystepuje wiecej celowych prob komunikowania \"jeszcze\", \"nie\" lub \"chce\" bez uzywania slow.",
  /* 328 */ "Niemowle uczy sie prostych zasad spolecznych przez powtarzalne, spokojne reakcje doroslych.",
  /* 329 */ "Moze szukac zabawki w kilku miejscach, jesli widzialo, gdzie zostala schowana.",
  /* 330 */ "Okolo jedenastego miesiaca dziecko czesto laczy ruch, gest i gaworzenie w wyrazne intencje komunikacyjne.",
  /* 331 */ "Dziecko moze podejmowac proby samodzielnego wstawania z podlogi przy meblu.",
  /* 332 */ "Stabilnosc stojaca poprawia sie przez codzienne, swobodne proby w bezpiecznej przestrzeni.",
  /* 333 */ "Niemowle moze robic kroki bokiem wzdluz mebli z coraz wieksza pewnoscia.",
  /* 334 */ "Moze pchac stabilny, odpowiednio ciezki przedmiot, cwiczac przenoszenie ciezaru ciala.",
  /* 335 */ "Dziecko lepiej przewiduje przebieg znanych aktywnosci, na przyklad kapieli lub wychodzenia z domu.",
  /* 336 */ "Moze podawac przedmiot na prosbe, zwlaszcza gdy rozumie sytuacje i gest doroslego.",
  /* 337 */ "Niemowle moze uzywac \"mama\" lub \"tata\" w kierunku konkretnej osoby, choc u czesci dzieci nastepuje to pozniej.",
  /* 338 */ "Zaczyna rozumiec proste emocje widoczne na twarzy i w glosie opiekuna.",
  /* 339 */ "Dziecko moze nasladowac klaskanie, potrzasanie glowa lub inne czesto ogladane gesty.",
  /* 340 */ "Okolo konca jedenastego miesiaca rozwija sie gotowosc do coraz bardziej samodzielnych prob ruchu i komunikacji.",
  /* 341 */ "Niemowle moze przejsc kilka krokow przy podtrzymaniu za rece, ale nie nalezy wymuszac tej aktywnosci.",
  /* 342 */ "Dziecko czesto wybiera samodzielna droge rozwoju ruchowego, na przyklad raczkowanie zamiast wczesnego chodzenia.",
  /* 343 */ "Moze probowac wkladac klocki lub przedmioty do pojemnika zgodnie z prostym wzorem zabawy.",
  /* 344 */ "Niemowle odkrywa funkcje przedmiotow, na przyklad ze szczotka mozna czesac wlosy.",
  /* 345 */ "Dziecko moze wskazywac lub podawac przedmiot, aby rozpoczac wspolna interakcje.",
  /* 346 */ "Coraz czesciej rozumie slowa uzywane w konkretnych, codziennych sytuacjach.",
  /* 347 */ "Moze reagowac na proste polecenie jednoczesciowe, takie jak \"daj pilke\", jesli zna slowa i kontekst.",
  /* 348 */ "Niemowle wyraza swoje preferencje wyraznym ruchem glowy, gestem lub protestem.",
  /* 349 */ "Rozwija pamiec osob i miejsc, dlatego moze silnie reagowac na rozlake albo zmiane rutyny.",
  /* 350 */ "Okolo dwunastego miesiaca wiele dzieci wykazuje duza roznorodnosc w tempie chodzenia, mowienia i samodzielnosci.",
  /* 351 */ "Dziecko moze samodzielnie stac przez kilka sekund lub dluzej, jesli jest na to gotowe.",
  /* 352 */ "Niektore dzieci wykonuja pierwsze samodzielne kroki, podczas gdy inne nadal preferuja raczkowanie.",
  /* 353 */ "Niemowle moze pchac zabawke na kolkach, wykorzystujac ja jako wsparcie w ruchu.",
  /* 354 */ "Dziecko coraz sprawniej uzywa chwytu pesetowego, podnoszac drobne bezpieczne kawalki jedzenia.",
  /* 355 */ "Probuje jesc palcami i poznaje rozne konsystencje oraz smaki.",
  /* 356 */ "Moze wypowiadac pierwsze slowo uzywane konsekwentnie w konkretnym znaczeniu, ale nie jest to obowiazkowe w tym wieku.",
  /* 357 */ "Dziecko rozumie znaczenie wiekszej liczby slow, niz potrafi samodzielnie powiedziec.",
  /* 358 */ "Wspolne wskazywanie obrazkow i ich nazywanie wspiera rozwoj rozumienia mowy.",
  /* 359 */ "Niemowle moze nasladowac proste zadania, takie jak wytarcie stolika lub przykrycie lalki.",
  /* 360 */ "Okolo pierwszych urodzin dziecko wchodzi w okres intensywnego rozwoju samodzielnosci, jezyka i ruchu.",
  /* 361 */ "Dziecko moze celowo przynosic przedmiot doroslemu, aby pokazac zainteresowanie lub poprosic o pomoc.",
  /* 362 */ "Coraz lepiej rozumie, ze rozne przedmioty sluza do roznych dzialan.",
  /* 363 */ "Niemowle moze budowac prosta wieze z dwoch klockow z pomoca lub samodzielnie.",
  /* 364 */ "Dziecko moze nasladowac uzycie telefonu, kubka, lyzki albo szczotki w zabawie.",
  /* 365 */ "Pierwsze urodziny sa punktem orientacyjnym, a nie terminem, do ktorego dziecko musi osiagnac konkretny zestaw umiejetnosci.",
  /* 366 */ "Dziecko moze pewniej przemieszczac sie przy meblach albo wykonywac samodzielne kroki.",
  /* 367 */ "W czasie zabawy zaczyna celowo wybierac przedmiot, ktory najlepiej pasuje do jego zamiaru.",
  /* 368 */ "Niemowle moze probowac wkladac przedmioty jeden w drugi lub umieszczac je w pojemniku.",
  /* 369 */ "Dziecko komunikuje wiecej przez gesty, spojrzenie, wskazywanie i wokalizacje.",
  /* 370 */ "Moze okazywac dume po udanym dzialaniu, szukajac reakcji opiekuna.",
  /* 371 */ "Niemowle rozwija poczucie sprawczosci, gdy zauwaza skutki wlasnych dzialan.",
  /* 372 */ "Dziecko moze odtwarzac znane czynnosci w prostych zabawach nasladowczych.",
  /* 373 */ "Coraz czesciej rozumie proste zakazy, ale nadal potrzebuje zabezpieczonego otoczenia zamiast samych slownych ograniczen.",
  /* 374 */ "Moze probowac pomagac podczas ubierania, wkladajac reke lub noge w odpowiednim momencie.",
  /* 375 */ "Okolo dwunastego i pol miesiaca dziecko coraz wyrazniej komunikuje wlasna wole.",
  /* 376 */ "Dziecko moze uzywac jednego lub kilku slow, gestow albo dzwiekow ze stalym znaczeniem.",
  /* 377 */ "Rozumienie mowy rozwija sie przez nazywanie rzeczy i dzialan w codziennym kontekscie.",
  /* 378 */ "Niemowle moze wskazywac obrazek lub przedmiot po uslyszeniu jego nazwy.",
  /* 379 */ "Dziecko moze probowac samodzielnie korzystac z lyzeczki, choc wiekszosc jedzenia nadal wymaga pomocy.",
  /* 380 */ "Coraz lepiej pije z kubka z pomoca doroslego lub z odpowiedniego naczynia treningowego.",
  /* 381 */ "Moze probowac wspinac sie na niskie meble, co zwieksza potrzebe stalego zabezpieczenia przestrzeni.",
  /* 382 */ "Niemowle testuje granice, powtarzajac dzialanie mimo reakcji doroslego.",
  /* 383 */ "Dziecko moze protestowac przy zmianie aktywnosci, poniewaz silniej rozwija niezaleznosc.",
  /* 384 */ "Wspolne rytualy pomagaja mu przewidywac przejscia miedzy zabawa, posilkiem i snem.",
  /* 385 */ "Okolo trzynastego miesiaca dziecko uczy sie przez powtarzanie krotkich, codziennych czynnosci.",
  /* 386 */ "Dziecko moze przejsc kilka krokow samodzielnie, zatrzymac sie i odzyskac rownowage.",
  /* 387 */ "Niemowle moze nadal preferowac raczkowanie, poniewaz jest ono szybkie i daje mu pewnosc.",
  /* 388 */ "Dziecko rozwija koordynacje, schylajac sie po przedmiot i ponownie prostujac cialo.",
  /* 389 */ "Moze probowac toczyc lub rzucac pilke w kierunku doroslego.",
  /* 390 */ "Niemowle zaczyna rozumiec prosta wymiane w zabawie, na przyklad naprzemienne turlanie pilki.",
  /* 391 */ "Dziecko moze coraz celniej wkladac wieksze klocki do pudelka.",
  /* 392 */ "Uczy sie, ze przedmiot moze sluzyc jako narzedzie, na przyklad lyzka do mieszania.",
  /* 393 */ "Moze rozpoznawac osoby na zdjeciach i reagowac na ich nazwy.",
  /* 394 */ "Niemowle coraz swiadomiej wykorzystuje gesty \"daj\", \"jeszcze\" lub \"nie\".",
  /* 395 */ "Okolo trzynastego miesiaca rozwija sie jednoczesnie koordynacja ruchowa, rozumienie i wyrazanie intencji.",
  /* 396 */ "Dziecko moze probowac zdejmowac proste elementy garderoby, takie jak czapka lub skarpetka.",
  /* 397 */ "Niemowle moze wkladac rece w rekawy, gdy rutyna ubierania jest mu znana.",
  /* 398 */ "Dziecko rozpoznaje sekwencje dnia i moze reagowac na slowa zapowiadajace kapiel, spacer lub sen.",
  /* 399 */ "Moze nasladowac odglosy zwierzat albo dzwieki pojazdow podczas zabawy.",
  /* 400 */ "Czterechsetny dzien czesto przypada na okres silnego zainteresowania samodzielnym poruszaniem sie i nasladowaniem doroslych.",
  /* 401 */ "Dziecko moze uzywac wskazywania, aby dzielic sie zainteresowaniem, a nie tylko prosic o przedmiot.",
  /* 402 */ "Wspolne patrzenie na wskazany obiekt rozwija komunikacje spoleczna i slownictwo.",
  /* 403 */ "Niemowle moze rozumiec prosta prosbe o znalezienie znanego przedmiotu.",
  /* 404 */ "Dziecko coraz sprawniej wybiera zabawke odpowiednia do znanej czynnosci.",
  /* 405 */ "Moze probowac ukladac dwa lub trzy elementy jeden na drugim.",
  /* 406 */ "Niemowle moze siegac po ksiazeczke, gdy chce wspolnej aktywnosci.",
  /* 407 */ "Dziecko zaczyna przewracac kartonowe strony ksiazki, choc jeszcze nie zawsze pojedynczo.",
  /* 408 */ "Moze wskazywac wybrane obrazki po uslyszeniu prostego pytania.",
  /* 409 */ "Niemowle rozwija wieksza cierpliwosc do krotkich zabaw wymagajacych powtorzen.",
  /* 410 */ "Okolo trzynastego i pol miesiaca coraz chetniej uczestniczy w prostych wspolnych aktywnosciach.",
  /* 411 */ "Dziecko moze chodzic samodzielnie na krotkich dystansach lub pewnie poruszac sie przy podparciu.",
  /* 412 */ "Niemowle cwiczy zatrzymywanie, obracanie sie i zmiane kierunku podczas chodzenia.",
  /* 413 */ "Dziecko moze probowac wejsc na niski stopien z pomoca doroslego.",
  /* 414 */ "Rozwija kontrole dloni, bazgrzac kredka przeznaczona dla malych dzieci pod scislym nadzorem.",
  /* 415 */ "Niemowle moze probowac wkladac ksztalty do duzego sortera, uzywajac prob i bledow.",
  /* 416 */ "Dziecko coraz swiadomiej szuka pomocy, gdy nie moze wykonac zadania samodzielnie.",
  /* 417 */ "Moze uzywac pojedynczych slow lub wlasnych dzwiekow do nazywania waznych osob i rzeczy.",
  /* 418 */ "Niemowle rozumie wiecej prostych pytan wspartych gestem i sytuacja.",
  /* 419 */ "Dziecko moze reagowac na proste polecenie bez gestu, jesli jest ono bardzo znane.",
  /* 420 */ "Okolo czternastego miesiaca dziecko rozwija rownowage, narzedzia komunikacji i zabawe funkcjonalna.",
  /* 421 */ "Dziecko moze przynosic przedmiot, gdy chce pokazac swoje odkrycie.",
  /* 422 */ "Niemowle coraz wyrazniej wybiera miedzy dwiema propozycjami przez gest, wzrok lub slowo.",
  /* 423 */ "Dziecko moze probowac karmic lalke lub misia, nasladujac opieke doroslych.",
  /* 424 */ "Zabawa udawana zaczyna sie od prostych, znanych sytuacji zycia codziennego.",
  /* 425 */ "Niemowle moze dopasowywac niektore przedmioty do ich funkcji, na przyklad czapke do glowy.",
  /* 426 */ "Dziecko uczy sie rozumiec proste przeciwienstwa w dzialaniu, takie jak \"daj\" i \"wez\".",
  /* 427 */ "Moze wskazywac kilka czesci ciala, jesli czesto byly nazywane w zabawie.",
  /* 428 */ "Niemowle moze reagowac na proste piosenki gestem lub ruchem ciala.",
  /* 429 */ "Dziecko wyraza silne emocje, poniewaz chce samodzielnosci, ale nadal potrzebuje pomocy w regulacji.",
  /* 430 */ "Okolo czternastego miesiaca wspieraj samodzielnosc, pozostajac blisko i upraszczajac zadania.",
  /* 431 */ "Dziecko moze probowac jesc lyzka z coraz wieksza celowoscia.",
  /* 432 */ "Niemowle moze pic z kubka, choc rozlewanie jest naturalnym etapem nauki.",
  /* 433 */ "Dziecko moze zdejmowac latwe czesci ubrania, gdy chce uczestniczyc w samoobsludze.",
  /* 434 */ "Coraz czesciej wspolpracuje przy myciu rak, przewijaniu lub ubieraniu.",
  /* 435 */ "Niemowle moze rozumiec proste prosby dotyczace codziennych czynnosci.",
  /* 436 */ "Dziecko moze zaczac uzywac wiekszej liczby slow, ale tempo rozwoju mowy jest bardzo indywidualne.",
  /* 437 */ "Gdy nie uzywa slow, nadal skutecznie komunikuje sie gestem, wskazywaniem i zmiana intonacji.",
  /* 438 */ "Niemowle moze probowac powtarzac ostatnia sylabe zaslyszanego slowa.",
  /* 439 */ "Dziecko rozwija pamiec, odtwarzajac znana zabawe po przerwie.",
  /* 440 */ "Okolo czternastego i pol miesiaca dziecko coraz lepiej laczy rozumienie slow z konkretnym dzialaniem.",
  /* 441 */ "Dziecko moze szybciej chodzic, ale nadal czesto upada i potrzebuje bezpiecznej przestrzeni do cwiczen.",
  /* 442 */ "Niemowle moze probowac biegac, wykonujac szybkie kroki z szeroka podstawa.",
  /* 443 */ "Dziecko moze wchodzic na niski stopien z trzymaniem reki doroslego.",
  /* 444 */ "Uczy sie schodzic tylem lub z pomoca, gdy rozwija ocene odleglosci.",
  /* 445 */ "Niemowle moze toczyc pilke celowo w strone drugiej osoby.",
  /* 446 */ "Dziecko zaczyna nasladowac proste ruchy w piosenkach i zabawach rytmicznych.",
  /* 447 */ "Moze wykonac prosta sekwencje dwoch znanych dzialan, na przyklad wziac kubek i podac go doroslemu.",
  /* 448 */ "Niemowle moze rozumiec nazwy kilku codziennych przedmiotow bez potrzeby ich pokazywania.",
  /* 449 */ "Dziecko moze przegladac ksiazke i wskazywac ulubione obrazki.",
  /* 450 */ "Okolo pietnastego miesiaca rozwija sie wieksza sprawnosc chodu, zabawy nasladowczej i rozumienia mowy.",
  /* 451 */ "Dziecko moze budowac wieze z dwoch lub trzech klockow, wykorzystujac coraz lepsza kontrole rak.",
  /* 452 */ "Niemowle moze probowac ukladac przedmioty wedlug prostego podobienstwa, na przyklad wkladac klocki do pudelka.",
  /* 453 */ "Dziecko moze uzywac zabawki zgodnie z jej przeznaczeniem przez dluzsza chwile.",
  /* 454 */ "Moze samo rozpoczac zabawe udawana, na przyklad podajac \"napoj\" misiowi.",
  /* 455 */ "Niemowle uczy sie przez obserwacje doroslych i powtarzanie ich dzialan.",
  /* 456 */ "Dziecko moze wskazywac czesc ciala na prosbe, jesli zna jej nazwe.",
  /* 457 */ "Moze rozumiec krotkie pytania o znajome osoby, zwierzeta lub przedmioty.",
  /* 458 */ "Niemowle moze uzyc slowa, gestu lub dzwieku, aby zwrocic uwage na cos ciekawego.",
  /* 459 */ "Dziecko zaczyna laczyc emocje z prosta komunikacja, szukajac pocieszenia lub dzielac radosc.",
  /* 460 */ "Okolo pietnastego miesiaca codzienna rozmowa i wspolna zabawa sa wazniejszymi bodzcami niz nauka przez \"cwiczenia\".",
  /* 461 */ "Dziecko moze sprobowac samodzielnie wejsc na niski mebel, dlatego zabezpieczenie domu nadal wymaga regularnego przegladu.",
  /* 462 */ "Niemowle rozwija rownowage podczas chodzenia po roznych bezpiecznych powierzchniach.",
  /* 463 */ "Dziecko moze przysiasc, by podniesc zabawke, a nastepnie wrocic do stania.",
  /* 464 */ "Moze probowac kopnac pilke, choc ruch jest jeszcze malo precyzyjny.",
  /* 465 */ "Niemowle moze prowadzic prosta zabawke na sznurku lub pchac ja przed soba.",
  /* 466 */ "Dziecko cwiczy kontrole ruchu, probujac zatrzymac i ponownie uruchomic zabawke.",
  /* 467 */ "Moze rozpoczac krotka zabawe z innym dzieckiem przez obserwacje i rownolegle dzialanie.",
  /* 468 */ "Niemowle nadal uczy sie dzielenia i czekania, wiec konflikt o zabawke jest typowy.",
  /* 469 */ "Dziecko moze wyrazac frustracje intensywnie, gdy nie potrafi jeszcze powiedziec, czego potrzebuje.",
  /* 470 */ "Okolo pietnastego i pol miesiaca rozwoj emocjonalny wymaga spokojnych granic oraz pomocy w nazywaniu uczuc.",
  /* 471 */ "Dziecko moze wykonywac prosta prosbe dwuczesciowa, jesli jest bardzo znana i podana krok po kroku.",
  /* 472 */ "Niemowle moze przyniesc konkretna rzecz na polecenie, gdy rozpoznaje jej nazwe.",
  /* 473 */ "Dziecko zaczyna rozumiec, ze rozne osoby moga wykonywac rozne role w codziennych sytuacjach.",
  /* 474 */ "Moze szukac znanego przedmiotu w miejscu, w ktorym zwykle go przechowujecie.",
  /* 475 */ "Niemowle rozwija pamiec zdarzen przez odtwarzanie powtarzalnych rytualow.",
  /* 476 */ "Dziecko moze uzywac kilku slow ze znaczeniem albo stale rozwijac bogaty repertuar gestow.",
  /* 477 */ "Moze probowac laczyc slowo z gestem, aby komunikat byl skuteczniejszy.",
  /* 478 */ "Niemowle czesto rozumie znacznie wiecej, niz potrafi wyrazic slowami.",
  /* 479 */ "Dziecko moze odpowiedziec ruchem glowy na proste pytanie \"tak\" lub \"nie\", choc nie zawsze konsekwentnie.",
  /* 480 */ "Okolo szesnastego miesiaca dzieci roznia sie szczegolnie mocno liczba slow i tempem rozwoju chodu.",
  /* 481 */ "Dziecko moze probowac samodzielnie zalozyc czapke lub wlozyc stope do buta.",
  /* 482 */ "Niemowle moze wspolpracowac przy sprzataniu, wkladajac zabawki do pudelka po pokazaniu czynnosci.",
  /* 483 */ "Dziecko zaczyna rozumiec proste rutyny porzadkowania i przewidywac ich zakonczenie.",
  /* 484 */ "Moze wybierac miedzy dwiema rzeczami przez wskazanie, slowo albo siegniecie.",
  /* 485 */ "Niemowle moze zaczac uzywac prostych slow spolecznych, takich jak \"pa pa\", we wlasciwym kontekscie.",
  /* 486 */ "Dziecko moze reagowac na nazwe wlasnego odbicia lub na pytanie o siebie, choc pelne rozpoznanie siebie rozwija sie stopniowo.",
  /* 487 */ "Moze z zainteresowaniem ogladac fotografie bliskich osob i probowac je nazywac.",
  /* 488 */ "Niemowle rozwija wyobraznie w prostym udawaniu, na przyklad \"rozmowie\" przez zabawkowy telefon.",
  /* 489 */ "Dziecko moze wlaczyc doroslego do zabawy, podajac mu przedmiot albo patrzac oczekujaco.",
  /* 490 */ "Okolo szesnastego miesiaca relacja i wspolna uwaga staja sie glownym kanalem nauki jezyka.",
  /* 491 */ "Dziecko moze wspinac sie po bezpiecznych, niskich przeszkodach pod nadzorem doroslego.",
  /* 492 */ "Niemowle moze probowac schodzic po schodach tylem lub bokiem z pelna pomoca.",
  /* 493 */ "Dziecko rozwija koordynacje reka-oko, wkladajac wieksze elementy w odpowiednie otwory.",
  /* 494 */ "Moze bazgrac krotkimi ruchami kredka, jesli ma odpowiednie, bezpieczne materialy.",
  /* 495 */ "Niemowle moze przewracac strony ksiazki coraz bardziej celowo.",
  /* 496 */ "Dziecko zaczyna rozumiec, ze obrazek reprezentuje znany przedmiot lub osobe.",
  /* 497 */ "Moze wskazac jeden lub kilka obrazkow po prosbie doroslego.",
  /* 498 */ "Niemowle moze dopasowywac proste dzwieki do obiektow, na przyklad \"brum\" do auta.",
  /* 499 */ "Dziecko coraz chetniej nasladuje proste slowa i dzwieki w zabawie.",
  /* 500 */ "Piecsetny dzien to okres, w ktorym dziecko zwykle wyraznie pokazuje wlasne zainteresowania, wybory i emocje.",
  /* 501 */ "Dziecko moze probowac laczyc dwa znane dzialania w zabawie, na przyklad nakarmic misia i polozyc go spac.",
  /* 502 */ "Niemowle moze wykorzystywac przedmioty symbolicznie, choc zabawa udawana jest jeszcze bardzo prosta.",
  /* 503 */ "Dziecko moze przynosic buty lub kurtke, gdy rozpoznaje sygnaly zapowiadajace wyjscie.",
  /* 504 */ "Moze rozumiec prosta prosbe o odlozenie rzeczy na miejsce.",
  /* 505 */ "Niemowle rozwija samokontrole bardzo stopniowo, dlatego potrzebuje pomocy zamiast oczekiwania pelnego posluszenstwa.",
  /* 506 */ "Dziecko moze uzywac coraz wiekszej liczby slow, wlasnych okreslen lub gestow do komunikacji.",
  /* 507 */ "Moze wskazac bliska osobe, zwierze lub rzecz po uslyszeniu jej nazwy.",
  /* 508 */ "Niemowle moze reagowac na krotkie zdania zwiazane z biezaca czynnoscia.",
  /* 509 */ "Dziecko uczy sie rozmowy przez naprzemienne dzwieki, spojrzenia i odpowiedzi doroslego.",
  /* 510 */ "Okolo siedemnastego miesiaca rosnie zdolnosc do rozumienia codziennego jezyka i samodzielnego dzialania.",
  /* 511 */ "Dziecko moze chodzic pewniej, ale nadal ma szeroka postawe i potrzebuje czasu na nauke rownowagi.",
  /* 512 */ "Niemowle moze zaczac probowac biegac, podskakujac lub przyspieszajac niestabilnym krokiem.",
  /* 513 */ "Dziecko moze probowac wejsc po schodach z trzymaniem poreczy i reki doroslego.",
  /* 514 */ "Moze kucac podczas zabawy, a nastepnie samodzielnie wstawac.",
  /* 515 */ "Niemowle moze rzucac pilke do przodu, uzywajac calego ciala.",
  /* 516 */ "Dziecko moze probowac kopnac stojaca pilke, uczac sie planowania ruchu.",
  /* 517 */ "Moze budowac wyzsza wieze z klockow, jesli cwiczylo te zabawe.",
  /* 518 */ "Niemowle coraz dokladniej wklada przedmioty do pojemnikow roznej wielkosci.",
  /* 519 */ "Dziecko moze probowac odtworzyc prosta czynnosc obserwowana wczesniej u doroslego.",
  /* 520 */ "Okolo siedemnastego miesiaca swobodna zabawa ruchowa i nasladowcza wspiera wiekszosc obszarow rozwoju.",
  /* 521 */ "Dziecko moze uzywac slowa, gestu lub spojrzenia, aby poprosic o konkretna pomoc.",
  /* 522 */ "Niemowle moze pokazywac palcem, czego chce, i oczekiwac odpowiedzi.",
  /* 523 */ "Dziecko moze wskazywac cos ciekawego tylko po to, aby podzielic sie tym z opiekunem.",
  /* 524 */ "Moze rozumiec prosta roznice miedzy \"moje\" i \"twoje\" w codziennych powtarzalnych sytuacjach.",
  /* 525 */ "Niemowle zaczyna silniej zaznaczac wlasnosc i preferencje, co jest typowe dla rozwoju autonomii.",
  /* 526 */ "Dziecko moze reagowac na proste prosby o pomoc, na przyklad podac pieluszke.",
  /* 527 */ "Moze probowac wykonywac male zadania, aby uczestniczyc w zyciu domowym.",
  /* 528 */ "Niemowle uczy sie zasad przez przewidywalne granice, krotkie komunikaty i przekierowanie uwagi.",
  /* 529 */ "Dziecko moze szybciej przechodzic od radosci do frustracji, poniewaz emocje wyprzedzaja jeszcze zdolnosc ich regulacji.",
  /* 530 */ "Okolo siedemnastego i pol miesiaca pomoc w nazywaniu emocji wspiera rozwoj spoleczno-emocjonalny.",
  /* 531 */ "Dziecko moze zaczac laczyc dwa elementy komunikacji, na przyklad gest z dzwiekiem lub slowem.",
  /* 532 */ "Niemowle moze uzywac kilku lub kilkunastu slow, ale szeroki zakres tempa jest nadal prawidlowy.",
  /* 533 */ "Dziecko moze probowac powtarzac krotkie slowa po doroslym, nawet jesli wymowa jest jeszcze niejasna.",
  /* 534 */ "Moze odpowiadac na pytanie o znany przedmiot wskazaniem lub przyniesieniem go.",
  /* 535 */ "Niemowle rozumie coraz wiecej nazw czesci ciala, przedmiotow i codziennych czynnosci.",
  /* 536 */ "Dziecko moze uczestniczyc w prostym spiewaniu przez powtarzanie koncowek lub gestow.",
  /* 537 */ "Moze nasladowac sekwencje dwoch prostych ruchow, na przyklad klasniecie i machniecie.",
  /* 538 */ "Niemowle rozwija pamiec robocza, gdy pamieta, czego szukalo po krotkim rozproszeniu.",
  /* 539 */ "Dziecko moze rozwiazac prosty problem, odsuwajac przeszkode lub proszac doroslego o pomoc.",
  /* 540 */ "Okolo osiemnastego miesiaca dziecko staje sie coraz bardziej aktywnym uczestnikiem rozmowy i codziennych czynnosci.",
  /* 541 */ "Dziecko moze wykonywac samodzielne, pewniejsze kroki i zaczynac zmieniac tempo chodu.",
  /* 542 */ "Niemowle moze probowac biec, choc zatrzymywanie i omijanie przeszkod wciaz wymaga nauki.",
  /* 543 */ "Dziecko moze probowac wejsc na niski stopien z pomoca i coraz lepiej oceniac wysokosc.",
  /* 544 */ "Moze schodzic tylem z niskiej powierzchni, jesli wczesniej bylo tego spokojnie uczone.",
  /* 545 */ "Niemowle moze kopac pilke do przodu z rosnaca kontrola.",
  /* 546 */ "Dziecko moze rzucac mala miekka pilke nad lub przed siebie.",
  /* 547 */ "Moze budowac wieze z kilku klockow, wykorzystujac precyzyjniejszy chwyt i planowanie.",
  /* 548 */ "Niemowle moze bazgrac ruchem nadgarstka i przedramienia, zostawiajac slady na papierze.",
  /* 549 */ "Dziecko moze probowac dopasowac prosty ksztalt do otworu poprzez wielokrotne proby.",
  /* 550 */ "Okolo osiemnastego miesiaca rozwijaja sie rownolegle ruch, samodzielnosc, zabawa symboliczna i komunikacja.",
  /* 551 */ "Dziecko moze bawic sie \"na niby\", karmiac zabawke, przykrywajac ja lub usypiajac.",
  /* 552 */ "Niemowle moze uzywac jednego przedmiotu jako symbolu innego, na przyklad klocka jako telefonu.",
  /* 553 */ "Dziecko coraz chetniej odtwarza sceny znane z codziennego zycia.",
  /* 554 */ "Moze wskazac wiecej czesci ciala na sobie, lalce lub obrazku.",
  /* 555 */ "Niemowle moze rozumiec proste polecenia dwuczesciowe, gdy dotycza znanej rutyny.",
  /* 556 */ "Dziecko moze probowac nazywac osoby, zwierzeta i ulubione rzeczy.",
  /* 557 */ "Moze uzywac slow w przyblizonej wymowie, ktora z czasem stanie sie bardziej zrozumiala.",
  /* 558 */ "Niemowle wyraza swoje potrzeby coraz czesciej slowami zamiast wylacznie placzem.",
  /* 559 */ "Dziecko nadal potrzebuje duzo wsparcia w radzeniu sobie z rozczarowaniem i zmiana planu.",
  /* 560 */ "Okolo osiemnastego i pol miesiaca warto obserwowac rozwoj calosciowo, a nie porownywac dziecko dzien po dniu z rowiesnikami.",
  /* 561 */ "Dziecko moze pomagac przy prostych czynnosciach, takich jak wkladanie zabawki do pudelka.",
  /* 562 */ "Niemowle moze samodzielnie probowac zdjac but, skarpetke lub czapke.",
  /* 563 */ "Dziecko moze wybierac ubranie albo zabawke, wyraznie pokazujac swoja decyzje.",
  /* 564 */ "Moze uczestniczyc w karmieniu siebie lyzeczka, choc balagan pozostaje normalna czescia nauki.",
  /* 565 */ "Niemowle moze probowac wycierac rece lub twarz, nasladujac doroslego.",
  /* 566 */ "Dziecko rozpoznaje wlasne codzienne przedmioty i moze przynosic je na prosbe.",
  /* 567 */ "Moze reagowac na pytania dotyczace prostych wyborow przez wskazanie lub slowo.",
  /* 568 */ "Niemowle moze zaczac pokazywac wieksza troske o osobe, ktora udaje smutek lub bol.",
  /* 569 */ "Dziecko rozwija empatie przez obserwacje emocji i spokojne modelowanie reakcji opiekuna.",
  /* 570 */ "Okolo dziewietnastego miesiaca samodzielnosc rosnie, ale dziecko wciaz intensywnie potrzebuje bliskosci i wspolregulacji.",
  /* 571 */ "Dziecko moze chodzic po domu z coraz wieksza pewnoscia i omijac proste przeszkody.",
  /* 572 */ "Niemowle moze probowac biegac w kierunku wybranego celu.",
  /* 573 */ "Dziecko moze wspinac sie na niskie, bezpieczne elementy wyposazenia pod nadzorem.",
  /* 574 */ "Moze probowac przenosic przedmiot podczas chodzenia, cwiczac rownowage.",
  /* 575 */ "Niemowle moze zaczac nosic mala zabawke w jedno miejsce, aby kontynuowac zabawe.",
  /* 576 */ "Dziecko moze ukladac proste przedmioty wedlug funkcji lub podobnego wygladu.",
  /* 577 */ "Moze rozpoznawac i wskazywac coraz wiecej obrazkow w ksiazkach.",
  /* 578 */ "Niemowle moze nasladowac slowa slyszane podczas codziennych aktywnosci.",
  /* 579 */ "Dziecko uczy sie znaczenia prostych zdan poprzez towarzyszace im sytuacje.",
  /* 580 */ "Okolo dziewietnastego miesiaca rozwoj jezyka czesto jest szczegolnie widoczny w rozumieniu, gestach i probach mowienia.",
  /* 581 */ "Dziecko moze wykonac krotka sekwencje znanych dzialan po prostej prosbie.",
  /* 582 */ "Niemowle moze przyniesc konkretny przedmiot z innego pokoju, jesli dobrze zna jego nazwe i miejsce.",
  /* 583 */ "Dziecko moze rozwiazac prosty problem przez probe, obserwacje lub poproszenie o pomoc.",
  /* 584 */ "Moze uzywac prostych narzedzi w zabawie, takich jak lyzeczka do mieszania w miseczce.",
  /* 585 */ "Niemowle moze planowac prosta czynnosc, szukajac potrzebnego przedmiotu przed rozpoczeciem zabawy.",
  /* 586 */ "Dziecko moze nasladowac zachowania spoleczne, takie jak witanie sie lub zegnanie.",
  /* 587 */ "Moze probowac uzywac dwoch slow obok siebie, ale laczenie slow nie musi pojawic sie jeszcze teraz.",
  /* 588 */ "Niemowle moze komunikowac wiele tresci jednym slowem, gestem oraz intonacja.",
  /* 589 */ "Dziecko moze czesciej domagac sie samodzielnosci, a jednoczesnie protestowac, gdy zadanie jest za trudne.",
  /* 590 */ "Okolo dziewietnastego i pol miesiaca najskuteczniejsze wsparcie to dawanie czasu, prostych wyborow i spokojnej pomocy.",
  /* 591 */ "Dziecko moze zaczac wskazywac przedmioty w ksiazce i oczekiwac ich nazwania.",
  /* 592 */ "Niemowle moze prosic o ulubiona piosenke, zabawke lub czynnosc przez slowo, dzwiek albo gest.",
  /* 593 */ "Dziecko moze rozpoznawac proste kategorie, takie jak zwierzeta, jedzenie lub pojazdy.",
  /* 594 */ "Moze probowac dopasowac przedmioty do ich miejsc, na przyklad wkladac lyzke do kuchennego pojemnika w zabawie.",
  /* 595 */ "Niemowle rozwija pamiec przez odtwarzanie codziennych sekwencji i rytualow.",
  /* 596 */ "Dziecko moze okazywac wieksze zainteresowanie innymi dziecmi, choc wspolna zabawa nadal jest glownie rownolegla.",
  /* 597 */ "Moze nasladowac zachowanie rowiesnika lub doroslego po krotkiej obserwacji.",
  /* 598 */ "Niemowle coraz wyrazniej komunikuje radosc, lek, zlosc i potrzebe pomocy.",
  /* 599 */ "Dziecko uczy sie regulacji emocji przede wszystkim dzieki spokojnej obecnosci i przewidywalnej reakcji opiekuna.",
  /* 600 */ "Okolo dwudziestego miesiaca dziecko zwykle jest mobilnym, ciekawym swiata uczestnikiem relacji, ktory rozwija sie we wlasnym tempie poprzez zabawe, ruch, rozmowe i bezpieczna bliskosc.",
};
